### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by xxzxcuzx-me** [Maheshkumar-Kakade/otp-generator#12]
Hi,
I would like to report to you a security issue within otp-generator and I need some way to disclose it privately. You could open your DMs on Twitter or provide me with an email address.

**Comment by xxzxcuzx-me** [comment]
@Maheshkumar-Kakade bump, maybe you didn't notice it, but I would really appreciate some response.

**Comment by ScSherifTarek** [comment]
@xxzxcuzx-me @Maheshkumar-Kakade I'm wondering if you've already managed to close that security risk?

**Comment by xxzxcuzx-me** [comment]
@ScSherifTarek Yes, it was resolved.
