### ISSUE TITLE
Wrong OTP generate

### ISSUE THREAD

**Issue by thangtv611** [Maheshkumar-Kakade/otp-generator#13]
I want to generate OTP with 6 digit (not include alphabets).

My function:
```
function generateOtp() {
    return generate(6, { upperCase: true, digits: true, specialChars: false, alphabets: false });
  }

```

But result:
KZFGCC

My environment:
OS: MacOs
Node: v12.22.2

**Comment by Maheshkumar-Kakade** [comment]
This is an issue in code and I will fix it today. Meanwhile will you please use workaround to set upperCase: false as well.
