### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by bkj281** [Maheshkumar-Kakade/otp-generator#14]
while executing the code it is throwing an error:
TypeError: crypto.randomInt is not a function
    at Object.generate (C:\Users\***\server\node_modules\otp-generator\index.js:36:32)

![image](https://user-images.githubusercontent.com/66874987/154233055-9136e0bc-d90b-4960-b157-65b47e030453.png)

**Comment by Maheshkumar-Kakade** [comment]
OTP generator version 4.0.0 need  "node": ">=14.10.0". If you have lower nodes version then use OTP version 3.0.0

**Comment by bkj281** [comment]
Ohk!
