### ISSUE TITLE
Only Digits OTP Length

### ISSUE THREAD

**Issue by kandarpkakkad** [Maheshkumar-Kakade/otp-generator#17]
When I get a string of 6 digits and 1st character is 0, the actual number becomes 5 digits. This should not happen. Can we add a check that the 1st character is not 0 in case of only digits OTP?

**Comment by Maheshkumar-Kakade** [comment]
0 at start is also valid OTP. Let me think if we can add option for same.

**Comment by Bankole2000** [comment]
I started using this package specifically to avoid this issue... @kandarpkakkad or @Maheshkumar-Kakade  - I dunno, has this issue been resolved? or is it still open?

**Comment by Maheshkumar-Kakade** [comment]
It is not fixed yet. I will fix it by 20th Jan.

**Comment by ameya051** [comment]
Have you fixed the issue?

**Comment by theseyan** [comment]
Like @Maheshkumar-Kakade pointed out, 0 is a valid start for an OTP. If your application removes the leading zeroes, you should be storing it as string and not a number.
This should really be behind an optional configuration flag, and not enabled by default.
