### ISSUE TITLE
TypeError: crypto.randomInt is not a function

### ISSUE THREAD

**Issue by raaneem** [Maheshkumar-Kakade/otp-generator#20]
Hi, getting the following error on NextJS

TypeError: crypto.randomInt is not a function

NodeJs version is 16.16.0

**Comment by hendyghsta** [comment]
> Hi, getting the following error on NextJS
> 
> TypeError: crypto.randomInt is not a function
> 
> NodeJs version is 16.16.0

same, I get error "TypeError: crypto.randomInt is not a function" 
NodeJs 12.14.1

**Comment by Maheshkumar-Kakade** [comment]
According to docs crypto.randomInt is added in NodeJs v14.10.0, v12.19.0. it should work for @raanym, @hendyghsta need to upgrade version to 12.19.0.
https://nodejs.org/docs/latest-v16.x/api/crypto.html#cryptorandomintmin-max-callback

**Comment by Maheshkumar-Kakade** [comment]
@raanym , I checked on runkit and it is working fine for version 16.18.0, here is link of same https://runkit.com/maheshkumar-kakade/63b4e9473abed7000851b7e7

**Comment by Maheshkumar-Kakade** [comment]
@raanym  and @hendyghsta are you able to resolve issue.
