### ISSUE TITLE
OTP length mismatch

### ISSUE THREAD

**Issue by web1experts** [Maheshkumar-Kakade/otp-generator#7]
When I have generated 4 digit OTP but I got 2 or 3 digits otp in some time

**Comment by Maheshkumar-Kakade** [comment]
what is options param?

**Comment by vivek8690** [comment]
I also faced the same issue 

`const options = {
        upperCase: false,
        specialChars: false,
        alphabets: false
    }`

**Comment by Maheshkumar-Kakade** [comment]
@vivek8690 Will you please confirm if issue is fixed.

**Comment by manan012** [comment]
I am facing the same issue. I have to generate 4 digit only numeric otp, but it generated 1 digit otp. current node version: 16.17.0 @Maheshkumar-Kakade

**Comment by Maheshkumar-Kakade** [comment]
Please share your code. I will check it.

**Comment by manan012** [comment]
`    const otp = otpGenerator.generate(length, {
      lowerCaseAlphabets: false,
      upperCaseAlphabets: false,
      specialChars: false,
    });`

**Comment by Maheshkumar-Kakade** [comment]
[test-package.zip](https://github.com/Maheshkumar-Kakade/otp-generator/files/9483707/test-package.zip)
@manan012 I am not able to reproduce issue. I have attached my sample code and it does produce correct OTP. You can use docker file in zip to run system independent in docker.
Node : OTP can start with 0 which is valid OTP
